version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    ignore:
      - dependency-name: "org.apache.tomcat.embed:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "com.amazonaws:*"
      - dependency-name: "software.amazon.awssdk:*"
      - dependency-name: "software.amazon.awssdk.crt:*"
      - dependency-name: "software.amazon.awscdk:*"
    groups:
      test-dependencies:
        patterns:
          - "org.junit.*"
          - "org.mockito.*"
          - "org.hamcrest.*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "com.amazonaws:*"
      - dependency-name: "software.amazon.awssdk:*"
      - dependency-name: "software.amazon.awssdk.crt:*"
      - dependency-name: "software.amazon.awscdk:*"
    groups:
      aws-dependencies:
        patterns:
          - "com.amazonaws:*"
          - "software.amazon.awssdk:*"
          - "software.amazon.awssdk.crt:*"
          - "software.amazon.awscdk:*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      jest:
        patterns:
          - "jest"
          - "jest-*"
          - "@jest/*"
