package de.otto.jlineup.web;

public enum State {
    BEFORE_PENDING,
    BEFORE_RUNNING,
    BEFORE_DONE,
    AFTER_PENDING,
    AFTER_RUNNING,
    FINISHED_WITHOUT_DIFFERENCES,
    FINISHED_WITH_DIFFERENCES,
    ERROR,
    DEAD
}
