jlineup:
  workingDirectory: /tmp/jlineup/
  screenshotsDirectory: report-{id}
  reportDirectory: report-{id}
  maxParallelJobs: 1
  chromeLaunchParameters: --use-spdy=off, --disable-dev-shm-usage
  cleanupProfile: true
  allowedUrlPrefixes:
    - https://www.otto.de
    - https://develop.otto.de
    - https://www.example.com
  lambda:
    functionName: jlineup-lambda

edison:
  application:
    title: JLineup
    description: Takes screenshots of webpages and checks for differences

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    loggers:
      enabled: true

spring:
  application:
    name: JLineup
  banner:
    location: classpath:banner.txt