jlineup:
  workingDirectory: /tmp/jlineup/
  screenshotsDirectory: report-{id}
  reportDirectory: report-{id}
  maxParallelJobs: 1
  chromeLaunchParameters: --use-spdy=off, --disable-dev-shm-usage

edison:
  application:
    title: JLineup
    description: Takes screenshots of webpages and checks for differences

management:
  endpoint:
    loggers:
      enabled: true

spring:
  application:
    name: JLineup
  banner:
    image:
      width: 200
      margin: 0