name: AWS Lambda Acceptance Tests

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/HISTORY.md'
      - 'docs/**'
  schedule:
    - cron: '0 9 * * *'

env:
  CHROME_VERSION: 146.0.7680.165

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: AWS Lambda acceptance tests
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JLINEUP_LAMBDA_ACCEPTANCE_TEST_ENABLED: true
          JLINEUP_LAMBDA_ACCEPTANCE_FORCE_DEPLOY: true
          AWS_REGION: eu-central-1
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          ./gradlew build assemble -x test
          ./gradlew :jlineup-lambda:test --tests '*LambdaAcceptanceTest*'
          JLINEUP_LAMBDA_ACCEPTANCE_FORCE_DEPLOY=false ./gradlew :jlineup-cli-lambda:test --tests '*CliLambdaAcceptanceTest*'