name: AWS Lambda Acceptance Tests

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/HISTORY.md'
      - 'docs/**'
  schedule:
    - cron: '0 9 * * *'

concurrency:
  group: aws-lambda-acceptance-test
  cancel-in-progress: false

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install dependencies (incl. AWS CDK)
        run: pnpm install
      - name: Add node_modules/.bin to PATH
        run: echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH
      - name: AWS Lambda acceptance tests
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          JLINEUP_LAMBDA_ACCEPTANCE_TEST_ENABLED: true
          JLINEUP_LAMBDA_ACCEPTANCE_FORCE_DEPLOY: true
          AWS_REGION: eu-central-1
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          ./gradlew build assemble -x test
          ./gradlew :jlineup-lambda:test --tests '*LambdaAcceptanceTest*'
          JLINEUP_LAMBDA_ACCEPTANCE_FORCE_DEPLOY=false ./gradlew :jlineup-cli-lambda:test --tests '*CliLambdaAcceptanceTest*'