# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/HISTORY.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'


jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DISPLAY: :0
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle
    - name: Setup xvfb (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        # start xvfb in the background
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew dependencyCheckAggregate build
    - name: Archive dependency check report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: build/reports/dependency-check-report.html
